version: "3.9"

services:
  taskw:
    build: .
    image: taskw:0.0.2
    init: true
    volumes:
      - "./taskw.toml:/home/app/taskw.toml:ro"
      - "./taskrc:/home/app/taskrc:ro"
    deploy:
      restart_policy:
        condition: on-failure
